### ISSUE TITLE
Add a nonce parameter on unwrapping a CertRep

### ISSUE THREAD

**Issue by Javex** [Javex/libscep#10]
When a client receives the server's response, there SHOULD be a `recipientNonce` that matches the `senderNonce` that was used. The server is tasked with copying this over. The client SHOULD then verify the `recipientNonce` against that of the sender. However, just using the `senderNonce` field for this verification basically makes no sense at all as this has no security in it. Instead, the client should provide the nonce from the outside as use it for verificaiton.

So here is my idea: The unwrapping function for a `CertRep` accepts an optional argument `senderNonce` that takes the nonce generated for the request. _Iff_ this argument is provided, the client checks for the Nonce and fails with an error if it does not match. But the standard only states the nonce SHOULD be provided, so if the user does not provide a nonce, we can issue a warning instead (`scep_log` with level `WARN`).

But there remains an issue: What if the server does not provide a nonce? The protocol does not require it. However, the client cannot know that when providing the verification nonce. Several ideas:
- The client just warns about it (as above). This might harm security but is in line with the protocol.
- When a nonce is provided but the server does not set one, we fail as if comparison failed. This is against the standard as a server might not set it and we should accept that in any case. It actually requires the client to know about the servers behavior regarding this. More secure, less standard
- We provide a global option that creates a strict behavior: With this, such a nonce is always required. The default would be to run in non-strict mode and that behaves as in point 1. When its activated it behaves as in point 2. Thus we are compliant but the user can increase security on demand. This is also documented in #9.

@gknocke: What do you think?

**Comment by gknocke** [comment]
In my opinion this decision is up to the server and not to the client. If the client provides a nonce and the server doesn't, a warning is sufficient.

**Comment by Javex** [comment]
Okay, I'd like to have a flag here, too. So by default, we just issue a warning but if the client wants to make a nonce in the response required, they can set a flag.

Also if there is a nonce provided by both sides and it doesn't match, this is always an error.

**Comment by gknocke** [comment]
The server MUST include the senderNonce in his message. The client always has the possibility to check the senderNonce against his own nonce since this is a requirement for the response. I conclude that additionally providing the nonce is a MUST.

**Comment by Javex** [comment]
Oh wow the standard is a bit confusing here. So we can always expect the `senderNonce` to be set. And the server MUST provide a `recipientNonce` as well but is not forced to copy the `senderNonce` here (thus SHOULD). The verification of this nonce is, however, optional as well. Now I'm fully confused.

So yes, there must be a `recipientNonce` and no it is not necessarily the same (but SHOULD be). And the client SHOULD verify that it's the same. And yes: The client MUST provide the nonce from the outside, we check it against the `senderNonce` field of the reply. There MUST be a positive match here.

Additionally, the `recipientNonce` is checked to be equal, but a warning is issued if not. And we add a flag that turns this warning into an error if the user desires this.

**Comment by Javex** [comment]
You can find the live coding session of this one here: https://www.youtube.com/watch?v=P4lrxKKywkw
