### ISSUE TITLE
Strict certrep requirements

### ISSUE THREAD

**Issue by gknocke** [Javex/libscep#15]
SCEP has the following requierement:
All returned certificates MUST conform to [RFC5280]. But this defines X509v3 (!)
The issued certificate comes from the outside. This means we MUST NOT accept X509v1 certificates. OpenSSL usually generates v1 certificates if not specified otherwise. No PKI can run SCEP properly if it is issuing v1 certificates.
Intuitively I think this is a mistake in the RFC. Otherwise it would propably be explicitly mentioned in the SCEP protocol. But maybe I'm wrong and PKIs are usually issuing v3? Further investigation needed.

**Comment by Javex** [comment]
Okay, research showed that X.509v3 allows version v2 & v1 as well. Thus, no issue :)
