### ISSUE TITLE
return types

### ISSUE THREAD

**Issue by gknocke** [Javex/libscep#19]
when unwrapping, the content will be decrypted but not converted from bio to specific data types. Without additional functions, the function needs to guess which data type is expect. Whether the output is from the expected type or not needs to be checked by the function using the unwrapping.

**Comment by Javex** [comment]
This would turn `scep_unwrap` into an internal function like `scep_pkiMessage`. Then we need a function for each type that does the operation specific work by message type. It is correct that the response itself does not contain the information as to what type of response it is? In that case we really return the raw bio with the data and leave it up to the callee (library function per operation) to extract meaningful data from it.

**Comment by Javex** [comment]
2e84640a has done some work on this, it just needs some tests now. This will be done by #27 so this can be closed.
