### ISSUE TITLE
Handling enums

### ISSUE THREAD

**Issue by gknocke** [Javex/libscep#23]
My code claims that he is dealing with a Message consisting of failInfo badAlg, even if response if SUCCESS.

This is due to the fact, that SCEP_DATA includes enum FAIL_INFO. In case of CertRep SUCCESS or PENDING, this field will not be touched at all. Because of the usage of enums, FAIL_INFO is automatically initialized with 0 which is equivalent to badAlg.

In previous versions, the access resulted in a segmentation fault (which would be better in fact). What is the best way to deal with this problem? Adding a value for an invalid enum type and initializing all enums to it does not look good to me.

**Comment by Javex** [comment]
`failInfo` only has a meaning if `pkiStatus` indicates failure. Otherwise it has to be ignored. Where and how did you segfault? Where does the code claim that there is a problem? You need to provide examples so I can help you.
