### ISSUE TITLE
each function should be applicable with only 1 key

### ISSUE THREAD

**Issue by gknocke** [Javex/libscep#24]
Signing and decrypting is not necessarly be done by the same role. The user must have the opportunity to only provide one of them since signing/verifying and encrypting/decrypting may be done by different entities.

Unwrapping should therefore provide the functionallity to not require a key for decryption. Then, the encrypted content must be returned (the pkcs-7 enceloped structure instead of the bare decrypted content).

**Comment by Javex** [comment]
Could you explain when and why this might be necessary? Is this related to #25? Is it just a theoretical evaluation or a problem that exists right now, e.g. because openca-scep allows this?

**Comment by gknocke** [comment]
I just did some research and it seems that my assumption does not hold. 
I was thinking about the case that a RA is used and RA and CA are communicating via SCEP. However, decrypter and verifier of one message is still the same entity. Only the subject of the envelope differs from the subject of the encrypted csr.

**Comment by Javex** [comment]
So can we close this? Or is there something that needs to be done?
