### ISSUE TITLE
PKCS#7 add certificate?

### ISSUE THREAD

**Issue by Javex** [Javex/libscep#3]
pkcs7_add_certificate missing in pkiMessage. Do we need it?

**Comment by Javex** [comment]
http://tinyurl.com/kqxvlpr faulty
http://tinyurl.com/oc2mmpb correct
missing SignerCert on PKCSReq

**Comment by gknocke** [comment]
FIX: add a
PKCS7_add_certificate(p7data->p7, sig_cert);
right before
https://github.com/Javex/libscep/blob/develop/src/message.c#L20

This is how PKCSreq looks like after patch is applied:

-----BEGIN PKCS7-----
MIIHXAYJKoZIhvcNAQcCoIIHTTCCB0kCAQExDjAMBggqhkiG9w0CBQUAMIIDHAYJ
KoZIhvcNAQcBoIIDDQSCAwkwggMFBgkqhkiG9w0BBwOgggL2MIIC8gIBADGCAQIw
gf8CAQAwaDBbMQswCQYDVQQGEwJERTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8G
A1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRQwEgYDVQQDEwtmb28uYmFy
LmNvbQIJANN5WBNA9bjTMA0GCSqGSIb3DQEBAQUABIGAghiwdt9rFQL53TnINvEs
LwYpZdhU12mQT/AdBmmK1atlFEWdFdCftEmC19mRn/WltgRk5yzGYFz2KUggVVCz
chv8JWYc9gHcXoppjSHA6W37Es4GoKRuqKkdAqp/sPMbZrXAE9+iPkHej4KESbZQ
2mo8TvMpLqdYZnMEuf65+M4wggHlBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECOA1
W3m06kXugIIBwF6YsOoyJdc36erFjsopPfKhEyj9wwY0pFsB4TVd9OhICi8gpTQM
UPX8+gpM45X3glfzyArQUdSDInz8zNCwaARVpf5sJLtX6+cOvW0xKLvXSQOhOJFI
KAZOXnEkDOtqL/Ynh9WOtJ8JXbyF/AB91fx2xSAJf8eHu7uk3Iwiw/rrKU7ISAUf
lIU5SHFsZ9EuMmqUQz2POw6fDjDJU3aoMneMCunUhIutO5qPGP5jGWivBLXHbFnE
V0Q0JfAcUAJxTvAzmX86wJNhxl6uzvmzhHd3roqYsauxE9CHPdBax8LLhXEEBeY1
CWRaWWFmPavY14gTg67sV0mTniTZnblW3XCXslrnp/ORBkxz/1bPggLmib3PvqXz
jwE8S9oY5gYSTPQWVnEOmaKlHR/RG7iu34ZN/4h7uoqtLhz4TxPpFc10fNS4AwP9
1Sed0vm+jaMqRoVndyDFLKWJ6jZZctOJc/0AEW2tTKqKGm3eKhQhceOYAJ2cH6oe
HVpHN9fhrF6Fng5X9hyQ/zvADeQwEnHwwIHbM1cba2ilbYMEaGdpiRWs0l1tvzFh
rEZhXqOXgXqEtFtYt2JyD+ga7+yeXysHw72gggIzMIICLzCCAZgCCQDTeVgTQPW4
0zANBgkqhkiG9w0BAQUFADBbMQswCQYDVQQGEwJERTETMBEGA1UECBMKU29tZS1T
dGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRQwEgYDVQQD
Ewtmb28uYmFyLmNvbTAgFw0xNTAyMjYxMjAwMzlaGA8yMTE1MDIwMjEyMDAzOVow
WzELMAkGA1UEBhMCREUxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNVBAoTGElu
dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEUMBIGA1UEAxMLZm9vLmJhci5jb20wgZ8w
DQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBANFEiTNrxDGehD636meTlC2yAmINuZn7
pU9CC4BudfdDAI2YdoB9h9YqRk773EYAveAfSMYg/ySzMlzz+yb8skZwctrocJYG
pgB4N0BpmkGt7VSK9qwT4mRXqL6G2Cvvifi4BBYPQ4c5JvYP43cDd7/Yb7Hg3Do8
tG16Zo6AXaFpAgMBAAEwDQYJKoZIhvcNAQEFBQADgYEAbUXoPS+AhHuO7T7KRdgw
JDLyr15dwUplGwtZT+MoOnnDMRWv/0VG4QUbBwvP5Jrrk/lRHKajXLmzrqaoiadG
zj6vCOh+zuf/KAOhQjvYtZyL0b727W1Sf2i7Cij+ublOOHR0hldn/XqR7hKfZ/uI
PnznQeKkVGjrEs223vtf7cIxggHbMIIB1wIBATBoMFsxCzAJBgNVBAYTAkRFMRMw
EQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBXaWRnaXRzIFB0
eSBMdGQxFDASBgNVBAMTC2Zvby5iYXIuY29tAgkA03lYE0D1uNMwDAYIKoZIhvcN
AgUFAKCBxzASBgpghkgBhvhFAQkCMQQTAjE5MBwGCSqGSIb3DQEJBTEPFw0xNTAz
MDYxNzA5MjBaMB8GCSqGSIb3DQEJBDESBBCtHFqNv/AzDyXKeViwLHYwMCAGCmCG
SAGG+EUBCQUxEgQQfS5VQKFVbVka8axx9jqboDBQBgpghkgBhvhFAQkHMUITQDJG
M0M4ODExNEMyODNFOUE2Q0Q1N0JCODI2NkNFMzEzREIwQkVFMERBRjc2OUQ3NzBD
NEU1RkZCOUM0QzEwMTYwDQYJKoZIhvcNAQEBBQAEgYC8nIncg0fQrgmqXfrwy7HR
XxpdqQuNwcM77sUidBxqfxWsR3UVAznNlFTyDWeKilGmMk4Y5QzJ4NQqIjJBF1p8
br0BwApI+Wj0BhOfLELo6ncTcCVUT5Xgofwu44xlPsm4wurTjCMVDDBrp6KC/OYp
scHLToqN4eZffrP9RQs8qg==
-----END PKCS7-----

**Comment by Javex** [comment]
I actually have a problem here: I cannot find the part in the specification that requires this. I don't see it explicitly mentioned so if it is required (is it?) then it must be part of some operation of the PKCS#7 standard or similar (e.g. as part of the signed data stuff).

The issue here is that there might be more that is missing and so I want to make sure to add everything correctly. Do you have any idea where this is mentioned in the [standard](https://tools.ietf.org/html/draft-nourse-scep-23)? I guess it should be mentioned in [Section 3.1](https://tools.ietf.org/html/draft-nourse-scep-23#section-3.1) if it were explicitly mentioned.

**Comment by gknocke** [comment]
Not adding the certificate would be compliant and therfore possible. The resulting structure is still valid since it is not a required field, neither in PKCS7 nor in the SCEP. However, when signing or verifying the structure this certificate needs to be available.
When not sending the certificate, the server side needs to obtain the certificate from some place. Signing a message without providing the corresponding certificate may not be useful. Since OpenSSLs' default behaviour adds this, I suggest to do it in the same way.

However, we could introduce an additional parameter which enables the possibility to not provide the certificate. This would then be an equivalent to OpenSSL's -nocerts parameter

**Comment by Javex** [comment]
You are correct. As a reference, PKCS#7, [Section 9.1](https://tools.ietf.org/html/rfc2315#section-9.1) states that

```
  certificates is a set of PKCS #6 extended
  certificates and X.509 certificates. It is intended that
  the set be sufficient to contain chains from a recognized
  "root" or "top-level certification authority" to all of the
  signers in the signerInfos field. There may be more
  certificates than necessary, and there may be certificates
  sufficient to contain chains from two or more independent
  top-level certification authorities. There may also be
  fewer certificates than necessary, if it is expected that
  those verifying the signatures have an alternate means of
  obtaining necessary certificates (e.g., from a previous set
  of certificates).
```

So yes, we may omit it as it is never required but it is a good idea to include anything up to the root.

We generally have two cases here
- The signer cert is selfsigned. In that case we only include this cert as there is no chain.
- The signer cert is a valid certificate in a chain that may be arbitrarily long. The current scenario is clearly that there s PKI server that has the information on all certificates to complete the chain. Thus, we only include the leaf certificate which we use to sign with. However, it might be useful in the future to include additional certificates to form the chain so that the recipient only needs the root certificate. Since this also requires some knowledge about the PKI process (e.g. if the server can't complete the chain, which will be the CA cert for the newly issued certificate; it can't be the old one as we just said we need to give it to the server).
