### ISSUE TITLE
Missing content type on pkiMessage

### ISSUE THREAD

**Issue by Javex** [Javex/libscep#4]
Forgot to set contentType on pkiMessage

**Comment by Javex** [comment]
sscep does this https://github.com/certnanny/sscep/blob/develop/pkcs7.c#L265

**Comment by Javex** [comment]
Again, standards confuse me. Here is what the protocol requires as signed attributes:
- an SCEP transactionID attribute
- an SCEP messageType attribute
- an SCEP senderNonce attribute
- any attributes required by PKCS#7 [RFC2315] [Section 9.2](https://tools.ietf.org/html/rfc2315#section-9.2)

And Section 9.2 states this:

```
authenticatedAttributes is a set of attributes
that are signed (i.e., authenticated) by the signer. The
field is optional, but it must be present if the content
type of the ContentInfo value being signed is not data. If
the field is present, it must contain, at a minimum, two
attributes:

1. A PKCS #9 content-type attribute having
   as its value the content type of the
   ContentInfo value being signed.

2. A PKCS #9 message-digest attribute,
   having as its value the message digest
   of the content (see below).
```

And since `the contentType in contentInfo MUST be data ({pkcs-7 1})` per SCEP spec, I read from that, that we may in fact omit it. Do you agree @gknocke? Or is there an oversight? We could of course just include it but that is only doing it halfway: Then we'd need point 2 as well.

**Comment by gknocke** [comment]
The SCEP standard reduces the amount of possibilities provided by PKCS#7 because only a subset is needed. Different content types are out scope of SCEP and we can omit it. However, we can not ignore the standard PKCS#7 attributes. Luckliy, OpenSSL does this for us.

**Comment by Javex** [comment]
I gather from that we can omit it and thus close this?
