### ISSUE TITLE
Protocol Modes

### ISSUE THREAD

**Issue by Javex** [Javex/libscep#9]
When another implementation diverts from the protocol slightly (e.g. not setting a required value) there should be an option to run in compliance/legacy: This will ignore certain attributes that would normally be required but the other end fails on this. This should then be fixed on the other side, but we cannot rely on this and so offer this mode.

A second mode would be strict. This mode requires additional values, e.g. for security, to be set that are not strictly required by the protocol (often denoted by SHOULD). Thus a user can enhance security if they know they only run against an instance the does indeed follow the suggestion in the specification.

I'd say these modes should be exclusive. I don't see a case where we want a strict legacy mode... However, this might need investigation beforehand, maybe there is such a case and we really want to support it.

**Comment by gknocke** [comment]
Ideally there is a config file in which the user sets flags how to handle each optional requirement. Config files would also be useful to define certificate stores etc.
When creating messages, all possible SHOULD requirements should  ;) be implemented. I suggest to just evaluate the MUST requirements on receiving messages. Everything else can be implemented afterwards.

**Comment by Javex** [comment]
Okay, I implemented this in e7c803e as a flag system as you suggested: All flags to be created need to be named and defined in such a way that if they are not set, the default behavior is used, i.e. there are no default flags.

This example of `SCEP_SKIP_SIGNER_CERT` shows this: Instead of having an option to _add_ a cert, we have one to skip addding it. Thus adding == default action.
